services:

  nginx:
    image: nginx:latest
    container_name: nginx-server
    restart: always
    networks:
      - dbnet
    expose:
      - 8088
    ports:
      - "80:8088"
    volumes:
      - ./sitekit/static:/app/www/sitekit/static
      - ./sitekit/media:/app/www/sitekit/media
      - ./sitekit/logs:/app/www/sitekit/logs
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - sitekit


  sitekit:
    build: ./sitekit
    image: sitekit
    container_name: sitekit
    restart: always
    command: "gunicorn -c gunicorn.py sitekit.wsgi"
    env_file:
      - .env
    links:
      - "postgres:dbps"
    networks:
      - dbnet
    volumes:
      - ./sitekit:/app/www/sitekit
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis


  redis:
    image: redis:7
    container_name: sitekit_redis
    restart: always
    networks:
      - dbnet
    ports:
      - "6379:6379"


  adminer:
    image: adminer
    container_name: adminer
    ports:
      - "8080:8080"
    links:
      - "postgres:db"
    networks:
      - dbnet
    depends_on:
      - postgres


  postgres:
    image: postgres:17-alpine
    container_name: psgr
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    networks:
      - dbnet

networks:
  dbnet:
    driver: bridge

volumes:
  postgres-data: